language: node_js
node_js:
- '7'
- '6'
- '5.1'
- '4.2'
install:
- npm install
- npm install react@15.5.1
script:
- npm run test
- npm run build
after_success:
- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'